version: 2.1
jobs:
    linux:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-linux-dependencies-{{ checksum "package.json" }}
                      - v1-linux-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-linux-dependencies-{{ checksum "package.json" }}
            - run: npm build
