name: Deployment CI

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Publish website
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: SSH into server
              uses: appleboy/scp-action@master
              env:
                  host: ${{ secrets.HOST_NAME }}
                  username: ${{ secrets.USER_NAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.PORT }}
                  script_stop: true
                  script: |
                      cd ${{ secrets.SITE_PATH }}
                      yarn prep && yarn deploy
