name: Build CI

on:
    push:
        branches: [development]
    pull_request:
        branches: [master, development]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build
