name: Deployment CI

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Publish website
        #needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: SSH into server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST_NAME }}
                  username: ${{ secrets.USER_NAME }}
                  key: ${{ secrets.SSH_KEY }}
                  passphrase: ""
                  port: ${{ secrets.PORT }}
                  debug: true
                  script_stop: true
                  script: |
                      cd ${{ secrets.SITE_PATH }}
                      pwd
                      #yarn prep && yarn deploy
